// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:notey/api/api_keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: firebaseWebApi,
    appId: '1:229131010297:web:13da6c057ba574095d2228',
    messagingSenderId: '229131010297',
    projectId: 'notey-ca7fe',
    authDomain: 'notey-ca7fe.firebaseapp.com',
    storageBucket: 'notey-ca7fe.appspot.com',
    measurementId: 'G-S0QG5JC2VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: firebaseAndroidApi,
    appId: '1:229131010297:android:8f1fbdfc551914a95d2228',
    messagingSenderId: '229131010297',
    projectId: 'notey-ca7fe',
    storageBucket: 'notey-ca7fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: firebaseIOSApi,
    appId: '1:229131010297:ios:0c547344e37696575d2228',
    messagingSenderId: '229131010297',
    projectId: 'notey-ca7fe',
    storageBucket: 'notey-ca7fe.appspot.com',
    iosBundleId: 'com.furkangocuk.notey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: firebaseMacOSApi,
    appId: '1:229131010297:ios:0c547344e37696575d2228',
    messagingSenderId: '229131010297',
    projectId: 'notey-ca7fe',
    storageBucket: 'notey-ca7fe.appspot.com',
    iosBundleId: 'com.furkangocuk.notey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: firebaseWindowsApi,
    appId: '1:229131010297:web:74629804118489925d2228',
    messagingSenderId: '229131010297',
    projectId: 'notey-ca7fe',
    authDomain: 'notey-ca7fe.firebaseapp.com',
    storageBucket: 'notey-ca7fe.appspot.com',
    measurementId: 'G-4ZTRGZEGS4',
  );
}
